const questionsArray = [
	'What is something you want to do in the next year that you’ve never done before?',
	'What should you think about before getting into a relationship?',
	'Is humanity doomed to head in a destructive direction?',
	'What are some of the best advice you have ever gotten?',
	'What are your favourite three topics to talk about?',
	'If a genie granted you three wishes right now, what would you wish for?',
	'Is justice a human construct or is it independent of humans?',
	'Can artificial intelligence be creative?',
	'What is an uncommon belief you hold?',
	'Will racism cease to exist?',
	'Does an ideal government exist?',
	'What is your favourite quote and why?',
	'What are the five most important things on your bucket list?',
	'If pressing a button meant you received 5 million dollars but it also killed 5 people somewhere in the world, would you press it? What if the people were people you knew?',
	'Is competition good for two people in a relationship?',
	'If you had $100,000 to give away to any cause, which cause would you choose and why?',
	'What is an irrational fear that you have?',
	'What types of compliments do you like to hear?',
	'Are we the biggest threat to humanity?',
	'What do you do to impress others deliberately?',
	'What is the meaning of a good life?',
	'Who is someone you really admire?',
	'Is living life to the fullest possible?',
	"Would you rather be the absolute best at something that most people don't take seriously or be well above average, but not anywhere near the best, at something well respected?",
	'What are you curious about?',
	'What is happiness?',
	'Where are the top three places you want to travel to some day, and why?',
	'Who do you think of first when you think of "success"?',
	'Does fate exist?',
	'Other than money, what else have you gained from your current job?',
	'What is the meaning of rich and poor in the modern world?',
	'What is the craziest thing you have ever done and would you do it again?',
	'How do you express gratitude towards others? Give an example.',
	'What are your biggest goals in life?',
	'Do acts of kindness have a motive?',
	'What is something I’ve done for you that you are grateful for?',
	'Would the world be a better or worse place if religion ceased to exist?',
	"What could I do for you that I don't do now?",
	'Is religion conceptualised by one’s own belief system?',
	'Is poverty in society inevitable?',
	'Where do you see your life headed in the next year? What about the next five years?',
	'Is love simply physical desire or something more?',
	'What is your earliest memory?',
	'Why do people expect a universe full of randomness to be fair?',
	'What is the meaning of true love?',
	'Are we a minuscule part of intelligent life in the universe?',
	'What is your ideal weekend?',
	'What is the hardest thing you have ever been through?',
	'What did you learn yesterday?',
	'What does intimacy mean to you?',
	'What are three things that make you happy instantly?',
	'Who do you trust?',
	'What two questions would you ask to get the most information about who a person truly is?',
	'What do you value more – security or freedom?',
	'Can achieving nothing make a person happy?',
	'What are five things you are thankful for right now?',
	'What type of scent do you like on a person you are attracted to?',
	'Is the most important purpose in life to find happiness?',
	'In 10 years, how would you like to describe your life?',
	'Are highly intelligent people less happy than individuals with average intelligence?',
	'Will a world without reliance on modern technology make any progress?',
	'When you look into the past, what do you miss the most?',
	'Does life require a purpose and a goal?',
	'When was the last time you were in love?',
	'Where do you see yourself living when you retire?',
	'Will stricter laws make a better world?',
	'Is having a big ego a negative or positive trait?',
	'If you could enter a time machine, what time period would you go to?',
	'Who is your role model in life?',
	'Who is your role model in love?',
	'What do you miss about being a kid?',
	'Is human potential capable of anything?',
	'Is it better to have loved and lost, than to have never loved?',
	'Does spirituality make you a happy person?',
	'Is it more important to be respected or liked?',
	'If you could take a year-long paid sabbatical, what would you do?',
	'In what situations do you feel most comfortable sharing your perspective?',
	'Do parallel universes exist?',
	'Would you want to know you are going to die before hand or die suddenly without warning?',
	'What do you think is more important, exploring the world or yourself?',
	'Does jealousy have value in driving humans to improve or is it purely a negative emotion?',
	'What is the best part of being you?',
	'What is more important: doing the right thing or doing things right?',
	'What do you think about the most?',
	'Is there something you have dreamt of doing for a long time? Why haven’t you done it yet?',
	'What would your ideal romantic situation or relationship be?',
	'What will you fight for until the day you die?',
	'Are people ethically obliged to improve themselves?',
	'Do you believe in marriage? If so, how do you know if you love someone enough to marry them? If no, why not?',
	'How would you describe "freedom" in your own words?',
	'Would you rather be famous when you are alive and forgotten when you die, or unknown when you are alive but famous after you die?',
	'If humanity was put on trial by an advanced race of aliens, how would you defend humanity and argue for its continued existence?',
	'Is it better for a person to have a broad knowledge base or a deep knowledge base?',
	'Should governments make laws to protect people from hurting themselves?',
	'What is something you think is true about me, but you have never asked to confirm?',
	'Would you rather have a very successful partner or be successful yourself?',
	'What should be the goal of humanity?',
	'Would you rather be 100% confident in who you are, or be 100% confident that you are with the right person?',
	'Let’s alternate sharing three positive characteristics of each other.',
	'Is limiting immigration to developed countries right?',
	'If you found out you were going to die tomorrow, what would you do today?',
	'Is peace the only way to stop war?',
	'Tell me your life story in four minutes.',
	'What is the extent of freedom human beings should have?',
	'Have gadgets and apps taken away emotions?',
	'If you could change one thing about your appearance, what, if anything, would you change?',
	'Where do you go to find peace?',
	'How do you describe yourself to other people?',
	'Have you ever been hurt in the past and questioned the possibility of love?',
	'Would you rather lose all your old memories or never be able to make new ones?',
	'When is it okay to tell a lie?',
	'To what extent should a couple be transparent to each other?',
	'If someone gave you enough money to start a business – no strings attached – what kind of business would you want to start and why?',
	'What do you want your legacy to be?',
	'How do you best connect with others?',
	'What is a big waste of human potential?',
	'Is there a difference between loving and being in love? If so, how?',
	'If you could live in a virtual reality world of your own creation, would you?',
	'What do you understand today about your life or the world that you did not understand a year ago?',
	'If there were 26 hours in a day, what would you do more of?',
	'If you could write one new law that everyone had to obey, what law would you create?',
	'Could solely living your life for others create meaning for your life?',
	'What makes you feel accomplished?',
	'If everyone spoke their mind would this world be a better place?',
	'How do you think I should describe you to other people?',
	'What have you been proud of learning recently?',
	'What totally impresses you?',
	'What moments or events during your childhood shaped who you are now?',
	'Do knowledge and understanding make you content and happy as a person?',
	'Can rational thought exist without language?',
	'What is your love language - quality time, physical touch, words of affirmation, acts of service, and gifts?',
	'Who or what has recently changed your life?',
	'If all your episodic memories were erased, what kind of person would you be?',
	'If you could change three things about the country where you live, what would you change?',
	'What is your favourite recent memory we have shared together?',
	'What makes you happy?',
	'Should full access to the internet be a fundamental right?',
	'Is death a new beginning?',
	'Name four things we have in common.',
	'How does one find purpose in life?',
	'Would you say you have a "type"? If you have a current partner, does he/she fit that type?',
	'What are your biggest goals for 2020? How will you work to achieve them?',
	'How replaceable are you?',
	'What causes the most harm in the world, but is completely avoidable?',
	'What kind of old person would you like to become?',
	'If death is inevitable, why bother doing anything?',
	'Would a government run with algorithms, artificial intelligence, and statistics be better or worse than the government we have now?',
	'Is there ever a time when giving up makes sense?',
	'Have we become less happy in this age of technology?',
	'Does evil come from within, and if so why?',
	'How do you think you best express love?',
	'If you could have any job you wanted, that would it be?',
	'How important is it to you to be in love?',
	"What are your thoughts on having your elderly parents live with you in the future if they can't live on their own one day?",
	'Do you want children? If so, would it be a deal breaker if you found out your partner was unable to bear children?',
	'What are your top three strengths? Which strengths do you look for in a friend or partner?',
	'What is your favourite tradition?',
	'What is the one thing you think your current relationship is lacking?',
	'What do you think is missing in your life right now?',
	'Is it easier to love or to be loved?',
	'What makes love everlasting?',
	'What do you value most in a friendship?',
	'What desperately needs to be modernised?',
	'Will the world come to an end by human hands?',
	'Can memories be erased?',
	'What age do you feel on the inside?',
	'Who do you aspire to be more like?',
	'Is there an absolute way to attain a happy state of mind?',
	'If you could go back in time, what is one piece of advice you’d give to your younger self?',
	'How much effort should an individual put into not offending others?',
	'What is true friendship?',
	'What qualities make me special to you?',
	'If aliens attack, what will we do?',
	'Would you rather be hated or forgotten?',
	'If you could have three wishes from me, what would they be?',
	'If we could start a country from scratch, what would it be like?',
	'Tell me about a day you had that you will never forget.',
	'Is some degree of censorship necessary?',
	'In what ways are you your own worst enemy?',
	'Do you believe humans have free will?',
	'What is the next big step you would like to take?',
	'What is your biggest day-to-day challenge?',
	'Do you believe in soul mates? What about love at first sight?',
	'What makes you uncomfortable?',
	'What limitations should be imposed on free speech?',
	'How do you like to be comforted when you are upset?',
	'What was the first thing you thought when you met me?',
	'Would this world be better or be worse without teachers and formal education?',
	'What would you do on your “perfect” day?',
	'Tell me three things that happened in the last month that you are thankful for.',
	'How do you define human consciousness?',
	'What are your career goals and how could they affect your current or future relationship?',
	'Is there such a thing as a good death?',
	'Is what we perceive reality or just a construct of our minds? Is there an objective reality?',
	'Why do we do things we do not like to do?',
	'Does time have a beginning and end?',
	'What harsh truths do you choose to ignore?',
	'What is an example of injustice you recently witnessed?',
	'If someone you loved was killed in front of you, but someone created a copy of them that was perfect right down to the atomic level, would they be the same person and would you love them just as much?',
	'How do you think humans will become extinct?',
	'Where does your self-worth come from?',
	'If you had to give a 10-minute talk without preparation right now, what topic would you choose?',
	'Why do you think people cheat on their partners?',
	'What benefits does art provide society? Does art hurt society in any way?',
	'What do you attribute the biggest successes in your life to? How about your largest failures?',
	'What life-altering things should every human ideally get to experience at least once in their lives?',
	'Is it better to be a big fish in a small pond or a small fish in a big pond?',
	'By what standards do you judge yourself?',
	'How do you define "compatibility"?',
	'Does knowledge have intrinsic value or does it need to have a practical use to have value?',
	'What would you genetically change about humans to make them a better species?',
	'Where do you think is the most worthwhile place to find meaning in life? Work, family, hobby, religion, philosophy, helping others, all the small miracles, or something else entirely?',
	'Is a life that focuses on avoiding pain and seeking out pleasure a good and worthwhile life? Why or why not?',
	'What is the best path to find truth; science, math, art, philosophy, or something else?',
	'What in life is truly objective and not subjective?',
	'Would it be more frightening to discover that humans are the most advanced species in the universe or that we are far from being the most advanced species in the universe?',
	'What of your beliefs are absolutely true, or are all beliefs capable of being challenged and changed?',
	'Why are humans so confident in beliefs that cannot be proven?',
	'What are the pros and cons of doing something to escape from reality?',
	'Is the concept of “you” continuous or does past “you” continually disappear and fade into present and future “you”?',
	'What do you think determines a person’s sense of humour?',
	'When, if ever, is taking a human life justified?',
	'Is there such a thing as absolute morality?',
	'Can we know what happiness is without sadness?',
	'Is truth the same as reality? Why / why not?',
	'What are the key characteristics of a good friend?',
	'Would you look for a partner on a dating site or app? Why / why not?',
	'Would you rather have a job you love that pays very little, or a job you hate that pays a great deal of money?',
	'Are emotions rational or irrational?',
	'Should the government penalise those that live unhealthy lifestyles?',
	'Should organ donors be financially compensated?',
	'Should we limit the amount of money people can earn and save to avoid an unequal distribution of wealth?',
	'Is it always good to have choices?',
	'What things hold you back from doing the things that you really want to?',
	'Would you want a computer to make decisions that are always perfectly calculated, or do you prefer to have the power to make your own decisions?',
	'Are we obliged to help others?',
	'What does loyalty in a romantic relationship mean to you?',
	'Is it acceptable to torture terrorists to extract information?',
	'Would you choose to live in a computer simulation if it will make you a lot happier?',
	'Why do we respect the dead more than the living?'
];
