const questionsArray = [
	'What’s something you want to do in the next year that you’ve never done before?',
	'What should you think about before getting into a relationship?',
	'Is humanity doomed to head in a destructive direction?',
	'What’s some of the best advice you’ve ever gotten?',
	'What are your favourite three topics to talk about?',
	'If a genie granted you three wishes right now, what would you wish for?',
	'Is justice a human construct or is it independent of humans?',
	'Can artificial intelligence be creative?',
	'What is an uncommon belief you hold?',
	'Will racism cease to exist?',
	'Does an ideal government exist?',
	'What’s your favourite quote?',
	'What are the five most important things on your bucket list?',
	'If pressing a button meant you received 5 million dollars but it also killed 5 people somewhere in the world, would you press it? What if the people were people you knew?',
	'Is competition good for us as a couple?',
	'If you had $100,000 to give away to any cause, which cause would you choose and why?',
	'What is an irrational fear that you have?',
	'What types of compliments do you like to hear?',
	'Are we the biggest threat to humanity?',
	'What do you do to impress others deliberately?',
	'What is the meaning of a good life?',
	'Who’s someone you really admire?',
	'Is living life to the fullest possible?',
	"Would you rather be the absolute best at something that most people don't take seriously or be well above average, but not anywhere near the best, at something well respected?",
	'What goals do you have for us?',
	'What are you curious about?',
	"Is there anything we haven't tried that you'd like to?",
	'What is happiness?',
	'Where are the top three places you want to travel to some day, and why?',
	'Who do you think of first when you think of "success"?',
	'Does fate exist?',
	'Other than money, what else have you gained from your current job?',
	'What is the meaning of rich and poor in the modern world?',
	'What’s the craziest thing you’ve ever done and would you do it again?',
	'How do you express gratitude towards others? Give me an example.',
	'What are your biggest goals in life?',
	'Do acts of kindness have a motive?',
	'What’s something I’ve done for you that you’re grateful for?',
	'Will the world be a better place if religion ceased to exist?',
	"What could I do for you that I don't do now?",
	'Is religion conceptualised by one’s own belief system?',
	'Is poverty in society inevitable?',
	'Where do you see our marriage headed in the next year? What about the next five years?',
	'Is love simply physical desire or something more?',
	'What’s your earliest memory?',
	'Why do people expect a universe full of randomness to be fair?',
	'What is the meaning of true love?',
	'Are we a minuscule part of intelligent life in the universe?',
	'What’s your ideal weekend?',
	'What is the hardest thing you have ever been through?',
	'What did you learn yesterday?',
	'What are some things I can do outside of the bedroom to keep the feelings of intimacy going all day?',
	'What are three things that make you happy instantly?',
	'Who do you trust?',
	'What two questions would you ask to get the most information about who a person truly is?',
	'What do you value more – security or freedom?',
	'Can achieving nothing make a person happy?',
	'What are five things you’re thankful for right now?',
	'What type of scent do you like on a woman?',
	'Is the most important purpose in life to find happiness?',
	'In 10 years, how would you like to describe your life?',
	'Are highly intelligent people less happy than individuals with average intelligence?',
	'Will a world without reliance on modern technology make any progress?',
	'When you look into the past, what do you miss the most?',
	'Does life require a purpose and a goal?',
	'Have you ever been in love before me?',
	'Where do you see yourself living when you retire?',
	'Will stricter laws make a better world?',
	'Is having a big ego a negative trait of positive trait?',
	'If you could enter a time machine, what time period would you go to?',
	'Who is your role model in life? Who is your role model in love?',
	'What do you miss about being a kid?',
	'Is human potential capable of anything?',
	'Is it better to have loved and lost, than to have never loved?',
	'Can spirituality make you a happy person?',
	'Is it more important to be respected or liked?',
	'If you could take a year-long paid sabbatical, what would you do?',
	'In what situations do you feel most comfortable sharing your perspective?',
	'Do parallel universes exist?',
	'Would you want to know you are going to die before hand or die suddenly without warning?',
	'What do you think is more important, exploring the world or yourself?',
	'Does jealousy have value in driving humans to improve or is it purely a negative emotion?',
	'What is the best part of being you?',
	'What is more important: doing the right thing or doing things right?',
	'What do you think about the most?',
	'Is there something you’ve dreamed of doing for a long time? Why haven’t you done it yet?',
	'How would you hate for us to be described as a couple?',
	'What will you fight for until the day you die?',
	'What were you looking for when you found me? Were you looking for love at all?',
	'Are people ethically obliged to improve themselves?',
	'How do you know if you love someone enough to marry them?',
	'How would you describe "freedom" in your own words?',
	'Would you rather be famous when you are alive and forgotten when you die, or unknown when you are alive but famous after you die?',
	'If humanity was put on trial by an advanced race of aliens, how would you defend humanity and argue for its continued existence?',
	'How and where do you like to be touched?',
	'Is it better for a person to have a broad knowledge base or a deep knowledge base?',
	'Should governments make laws to protect people from hurting themselves?',
	"What is something you think is true about me, but you've never asked to confirm?",
	'Would you rather have a very successful partner or be successful yourself?',
	'What should be the goal of humanity?',
	'Would you rather be 100% confident in who you are, or be 100% confident that you are with the right person?',
	'Let’s alternate sharing three positive characteristics of each other.',
	'Is limiting immigration to developed countries right?',
	'If you found out you were going to die tomorrow, what would you do today?',
	'What did it feel like when you realised you were in love with me?',
	'Is peace the only way to stop war?',
	'Tell me your life story in four minutes.',
	'What is the extent of freedom human beings should have?',
	'Have gadgets and apps taken away emotions?',
	'How would you respond if my appearance drastically changed, either overnight (new haircut and different hair colour, for example) or over time (more/less muscle, weight gain/loss)?',
	'Where do you go to find peace?',
	'How do you describe me to other people?',
	'Are humans obligated to better themselves and will that make them happier?',
	'Have you ever been hurt in the past and questioned the possibility of love?',
	'Would you rather lose all your old memories or never be able to make new ones?',
	'When is it okay to tell a lie?',
	'If someone gave you enough money to start a business – no strings attached – what kind of business would you want to start and why?',
	'What do you want your legacy to be?',
	'How do you best connect with others?',
	'What is a big waste of human potential?',
	'Is there a difference between loving and being in love? If so, how?',
	'If you could live in a virtual reality world of your own creation, would you?',
	'What do you understand today about your life that you did not understand a year ago?',
	'If there were 26 hours in a day, what would you do more of?',
	'If you could write one new law that everyone had to obey, what law would you create?',
	'Does living your life for others make your life have meaning?',
	'What makes you feel accomplished?',
	'If everyone spoke their mind would this world be a better place?',
	'How do you think I should describe you to other people?',
	'What have you been proud of learning recently?',
	'What totally impresses you?',
	'What moments or events during your childhood shaped who you are now?',
	'Do knowledge and understanding make you content and happy as a person?',
	'Can rational thought exist without language?',
	'Is our relationship physical enough for you? What would make it better in your eyes?',
	'I want to be a good lover, and I want to be there for you. What can I do for you to be that woman or man?',
	'Who or what has changed your life?',
	'If all your memories were erased, what kind of person would you be?',
	'If you could change three things about the country where you live, what would you change?',
	'What’s your favourite recent memory we’ve shared together? Give me as many details as possible.',
	'What makes you happy?',
	'Should full access to the internet be a fundamental right?',
	'Is death a new beginning?',
	'Do atheists make their own gods?',
	'Name four things we have in common.',
	'How does one find purpose in life?',
	'Would you say you have a "type"? Do I fit what you thought you were looking for?',
	'What are your biggest goals for 2020? How will you work to achieve them?',
	'How replaceable are you?',
	'What causes the most harm in the world, but is completely avoidable?',
	'How do you imagine a day in the life of us with kids?',
	'What kind of old person would you like to become?',
	'If death is inevitable, why bother doing anything?',
	'Would a government run with algorithms, A.I., and statistics be better or worse than the government we have now?',
	'Is there ever a time when giving up makes sense?',
	'Have we become less happy in this age of technology?',
	'Does evil come from within, and if so why?',
	'How do you think you best express love?',
	'If you could have any job you wanted, that would it be?',
	'How important is it to you to be in love?',
	"What are your thoughts on having our elderly parents live with us if they can't live on their own one day?",
	'Would you stay with me if you found out I was unable to bear children?',
	'What are your top three strengths? Which strengths do you look for in a friend or partner?',
	'What’s your favourite tradition?',
	'What is the one thing you think our relationship is lacking?',
	'Is it easier to love or to be loved?',
	'Tell me about a relationship issue you’re having, and ask me for advice on how to fix it.',
	'Do you see our love lasting? Do you ever have any doubts?',
	'What do you value most in a friendship?',
	'What desperately needs to be modernised?',
	'Will the world come to an end by human hands?',
	'Can memories be erased?',
	'What age do you feel on the inside?',
	'Who do you aspire to be more like?',
	'Is there an absolute way to attain a happy state of mind?',
	'If you could go back in time, what’s one piece of advice you’d give to your younger self?',
	'How much effort should an individual put into not offending others?',
	'What is true friendship?',
	'What qualities make me special to you?',
	'If aliens attack, what will we do?',
	'Would you rather be hated or forgotten?',
	'If you could have three wishes from me, what would they be?',
	'If we could start a country from scratch, what would it be like?',
	'Tell me about a day you had that you’ll never forget.',
	'Is some degree of censorship necessary?',
	'In what ways are you your own worst enemy?',
	'What is the next big step you need to take?',
	'What is your biggest day-to-day challenge?',
	'Do you believe in soul mates? What about love at first sight?',
	'What makes you uncomfortable?',
	'Ideally how often would you like for us to be intimate?',
	'Are there limitations on free speech?',
	'How do you like to be comforted when you’re upset?',
	'What was the first thing you thought when you met me?',
	'Would this world be better or be worse without teachers and formal education?',
	'Do you have any fantasies you would like fulfilled?',
	'What would you do on your “perfect” day?',
	'Tell me three things that happened in the last week that you’re thankful for.',
	'How do you define consciousness?',
	'What is the first thing you think when you see me?',
	'What are your career goals and how could they affect our relationship?',
	'Is there such a thing as a good death?',
	'What is human consciousness?',
	'Is what we perceive reality or just a construct of our minds? Is there an objective reality?',
	'Why do we do things we do not like to do?',
	'Why do we respect the dead more than the living?'
];
